"""
Kubernetes CronJob generator for SuperAI goals/schedules (N206 expansion).

Generates production-ready YAML for:
- CronJob running `superai daemon tick` (or with --execute-goals)
- Optional ConfigMap for env
- Namespace defaults

Does not require a live cluster to generate; apply is optional via kubectl.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional


DEFAULT_IMAGE = "python:3.12-slim"
DEFAULT_SCHEDULE = "*/5 * * * *"  # every 5 minutes


def render_cronjob_yaml(
    *,
    name: str = "superai-goals-tick",
    namespace: str = "superai",
    schedule: str = DEFAULT_SCHEDULE,
    image: str = DEFAULT_IMAGE,
    execute_goals: bool = False,
    max_goals: int = 2,
    service_account: str = "superai",
    image_pull_policy: str = "IfNotPresent",
    suspend: bool = False,
    extra_env: Optional[Dict[str, str]] = None,
    resources: Optional[Dict[str, Any]] = None,
) -> str:
    """Return multi-document YAML string (Namespace + SA + CronJob)."""
    env = {
        "SUPERAI_NON_INTERACTIVE": "1",
        "SUPERAI_MOCK_MODE": "1",
        "MEMPALACE_MCP_ALLOW_PEER_WRITER": "1",
    }
    if extra_env:
        env.update({str(k): str(v) for k, v in extra_env.items()})

    tick_flags = ["daemon", "tick"]
    if execute_goals:
        tick_flags.append("--execute-goals")
    tick_flags += ["--max-goals", str(int(max_goals)), "--no-notify"]

    env_yaml = "\n".join(
        f'            - name: {k}\n              value: "{v}"' for k, v in sorted(env.items())
    )
    res = resources or {
        "requests": {"cpu": "50m", "memory": "128Mi"},
        "limits": {"cpu": "500m", "memory": "512Mi"},
    }
    # simple resources yaml
    res_yaml = textwrap.dedent(
        f"""
            resources:
              requests:
                cpu: "{res['requests']['cpu']}"
                memory: "{res['requests']['memory']}"
              limits:
                cpu: "{res['limits']['cpu']}"
                memory: "{res['limits']['memory']}"
        """
    ).rstrip()

    cmd_json = json.dumps(
        [
            "sh",
            "-c",
            "pip install -q superai 2>/dev/null || true; "
            "python -m pip install -q -e /app 2>/dev/null || true; "
            f"superai {' '.join(tick_flags)}",
        ]
    )

    yaml = f"""# Generated by SuperAI k8s_cronjob — do not hand-edit without regenerating
# superai daemon k8s-render
---
apiVersion: v1
kind: Namespace
metadata:
  name: {namespace}
  labels:
    app.kubernetes.io/name: superai
    app.kubernetes.io/component: goals-daemon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {service_account}
  namespace: {namespace}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app.kubernetes.io/name: superai
    app.kubernetes.io/component: goals-cronjob
spec:
  schedule: "{schedule}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: {str(suspend).lower()}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: superai
            app.kubernetes.io/component: goals-tick
        spec:
          serviceAccountName: {service_account}
          restartPolicy: Never
          containers:
          - name: superai-tick
            image: {image}
            imagePullPolicy: {image_pull_policy}
            command: {cmd_json}
{env_yaml}
{res_yaml}
"""
    return yaml.strip() + "\n"


def write_manifest(
    out_path: Path,
    **kwargs: Any,
) -> Dict[str, Any]:
    """Write YAML to path; return contract result."""
    from .spend_guard import ensure_public_result

    yaml = render_cronjob_yaml(**kwargs)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml, encoding="utf-8")
    return ensure_public_result(
        {
            "ok": True,
            "path": str(out_path),
            "bytes": len(yaml.encode("utf-8")),
            "schedule": kwargs.get("schedule") or DEFAULT_SCHEDULE,
            "namespace": kwargs.get("namespace") or "superai",
            "name": kwargs.get("name") or "superai-goals-tick",
            "execute_goals": bool(kwargs.get("execute_goals")),
            "apply_hint": f"kubectl apply -f {out_path}",
        },
        ok=True,
    )


def validate_yaml_text(yaml_text: str) -> Dict[str, Any]:
    """Lightweight validation without PyYAML dependency."""
    from .spend_guard import ensure_public_result

    text = yaml_text or ""
    checks = {
        "has_cronjob": "kind: CronJob" in text,
        "has_namespace": "kind: Namespace" in text,
        "has_schedule": "schedule:" in text,
        "has_superai_tick": "daemon" in text and "tick" in text,
        "concurrency_forbid": "concurrencyPolicy: Forbid" in text,
    }
    ok = all(checks.values())
    return ensure_public_result(
        {"ok": ok, "checks": checks, "docs": text.count("---") + 1},
        ok=ok,
    )


def try_kubectl_apply(path: Path, *, dry_run: bool = True) -> Dict[str, Any]:
    """Optional kubectl apply (dry-run client by default)."""
    import shutil
    import subprocess

    from .spend_guard import ensure_public_result

    if not shutil.which("kubectl"):
        return ensure_public_result(
            {
                "ok": False,
                "error": "kubectl_not_found",
                "hint": "Install kubectl or use k8s-render only",
            },
            ok=False,
        )
    args = ["kubectl", "apply", "-f", str(path)]
    if dry_run:
        args.append("--dry-run=client")
    try:
        proc = subprocess.run(
            args, capture_output=True, text=True, timeout=60
        )
        return ensure_public_result(
            {
                "ok": proc.returncode == 0,
                "returncode": proc.returncode,
                "stdout": (proc.stdout or "")[:4000],
                "stderr": (proc.stderr or "")[:2000],
                "dry_run": dry_run,
                "args": args,
            },
            ok=proc.returncode == 0,
        )
    except Exception as e:
        return ensure_public_result(
            {"ok": False, "error": str(e)[:300]}, ok=False
        )
